// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/shipdesk-logo/Axis.tsx": () => import("../components/mockups/shipdesk-logo/Axis.tsx"),
  "./components/mockups/shipdesk-logo/Beacon.tsx": () => import("../components/mockups/shipdesk-logo/Beacon.tsx"),
  "./components/mockups/shipdesk-logo/Grid.tsx": () => import("../components/mockups/shipdesk-logo/Grid.tsx")
};
