import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { adminApi } from "@/lib/adminApi";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { format } from "date-fns";

interface AdminReport {
  id: string; title: string; status: "DRAFT" | "PUBLISHED";
  generatedAt: string; weekStartDate: string; weekEndDate: string;
  generatedBy: "SCHEDULED" | "MANUAL";
  project: { name: string; workspace: { slug: string; name: string } };
}
interface PagedResponse { reports: AdminReport[]; total: number; page: number; pages: number; }

export function AdminReportsTab() {
  const [page, setPage] = useState(1);

  const { data, isLoading } = useQuery<PagedResponse>({
    queryKey: ["admin-reports", page],
    queryFn: () =>
      adminApi.get("/api/admin/reports", { params: { page } }).then((r) => r.data),
    staleTime: 30_000,
  });

  return (
    <div className="space-y-4">
      <div>
        <h2 className="text-lg font-semibold text-white">Reports</h2>
        <p className="text-sm text-white/50">{data?.total ?? "—"} AI-generated status reports</p>
      </div>

      <div className="rounded-xl border border-white/10 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-white/5 border-b border-white/10">
              <tr>
                {["Title", "Project / Workspace", "Week", "Status", "Generated By", "Date"].map((h) => (
                  <th key={h} className="text-left px-4 py-3 text-xs font-semibold text-white/50 uppercase tracking-wider whitespace-nowrap">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {isLoading
                ? Array.from({ length: 10 }).map((_, i) => (
                    <tr key={i}><td colSpan={6} className="px-4 py-3"><div className="h-4 bg-white/5 rounded animate-pulse" /></td></tr>
                  ))
                : data?.reports.map((r) => (
                    <tr key={r.id} className="hover:bg-white/[0.02] transition-colors">
                      <td className="px-4 py-3">
                        <div className="font-medium text-white max-w-[200px] truncate">{r.title}</div>
                      </td>
                      <td className="px-4 py-3">
                        <div className="text-white/80">{r.project.name}</div>
                        <div className="text-xs text-white/40 font-mono">{r.project.workspace.slug}</div>
                      </td>
                      <td className="px-4 py-3 text-white/50 text-xs whitespace-nowrap">
                        {format(new Date(r.weekStartDate), "MMM d")} – {format(new Date(r.weekEndDate), "MMM d, yyyy")}
                      </td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center text-xs px-2 py-0.5 rounded-full font-medium ${r.status === "PUBLISHED" ? "bg-emerald-500/15 text-emerald-400" : "bg-white/10 text-white/50"}`}>
                          {r.status.charAt(0) + r.status.slice(1).toLowerCase()}
                        </span>
                      </td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center text-xs px-2 py-0.5 rounded-full font-medium ${r.generatedBy === "SCHEDULED" ? "bg-indigo-500/15 text-indigo-400" : "bg-violet-500/15 text-violet-400"}`}>
                          {r.generatedBy === "SCHEDULED" ? "Auto" : "Manual"}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-white/50 text-xs whitespace-nowrap">
                        {format(new Date(r.generatedAt), "MMM d, yyyy")}
                      </td>
                    </tr>
                  ))
              }
            </tbody>
          </table>
        </div>
      </div>

      {data && data.pages > 1 && (
        <div className="flex items-center justify-between text-sm text-white/50">
          <span>Page {data.page} of {data.pages} · {data.total} total</span>
          <div className="flex gap-1">
            <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}
              className="p-1.5 rounded-lg border border-white/10 hover:bg-white/5 disabled:opacity-30 transition-colors">
              <ChevronLeft className="h-4 w-4" />
            </button>
            <button onClick={() => setPage(p => Math.min(data.pages, p + 1))} disabled={page === data.pages}
              className="p-1.5 rounded-lg border border-white/10 hover:bg-white/5 disabled:opacity-30 transition-colors">
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
